# Generated by Django 5.0.3 on 2024-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sellername', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('role', models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
